### ISSUE TITLE
Suggestion - Allow players to Purchase Cosmetics/Color changes

### ISSUE THREAD

**Issue by spiker5032** [LoneDev6/Wiki-CosmeticsCore#29]
Adding something like this will add much more functionality to this plugin not only as a cosmetics plugin but also as an economy driven plugin right out of the box.

Adding something like

  leather_backpack:
    display_name: "Leather Backpack"
    type: BODY_ITEM
    model:
      gui: potion:300001
      normal: potion:300001
      self: potion:300002
    dye:
      enabled: true
      default: "#542900"
    purchasable: true/false     "This would allow players to BUY cosmetics right through the wardrobe GUI then be able to equip them" 
      cost: 50000                       "This would be the cost of said cosmetic"
    colorcost: true/false           "This would allow players to BUY colors to change into upon equip"
     cost: 100                           "This would be the cost of the color change"
     
     I am also an advocate for some kind of way for the plugin to track if the player already owns the color so that they dont have to purchase a color multiple times when swapping colors..
     Maybe something like
     colorsave: true/false

**Comment by LoneDev6** [comment]
It's a good idea, but I think it would require a restructure of how the current GUI works.
I'll think about that in the future, another user also requested a way to add some sort of tokens to trade cosmetics with other players.

Anyway please move your suggestion to the correct page: https://github.com/PluginBugs/Issues-CosmeticsCore/issues
