### ISSUE TITLE
Suggestion - Remove all cosmetics when disguise.

### ISSUE THREAD

**Issue by spiker5032** [LoneDev6/Wiki-CosmeticsCore#30]
Exactly what the titles says.
When turning into a mob your still wearing cosmetics. It can look funny/cute but maybe a default true option in the config.yml like
RemoveCosmeticsOnDisguise: true/false

**Comment by LoneDev6** [comment]
Which plugin are you using to disguise yourself?

**Comment by LoneDev6** [comment]
Anyway please move your suggestion to the correct page: https://github.com/PluginBugs/Issues-CosmeticsCore/issues
